driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:

suites:
  - name: default
    attributes:
      chef_dotfiles:
        dotfiles_path: 'C:\Users\vagrant'
    named_run_list: myrun
