---
driver:
  name: localhost

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

verifier:
  name: serverspec
  patterns:
    - test/integration/default/inspec/default.rb

platforms:
  - name: macosx-10
    driver:
      name: localhost
  - name: windows-2012R2

suites:
  - name: default
    run_list:
      - test
