---
driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false

provisioner:
  name: dokken

platforms:
- name: centos-7
  driver:
    image: centos:7
    pid_one_command: /sbin/init

- name: debian-7.11
  driver:
    image: debian:7.11
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install openssl apt-transport-https lsb-release procps net-tools -y

- name: opensuse-leap
  driver:
    image: opensuse:leap
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN zypper --non-interactive install openssl aaa_base perl-Getopt-Long-Descriptive which hostname

- name: fedora-latest
  driver:
    image: fedora:latest
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y install which openssl which systemd-sysv initscripts wget net-tools

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: fedora-22
  driver:
    image: fedora:22
    pid_one_command: /sbin/init
    intermediate_instructions:

suites:
  - name: default
    attributes:
      chef_dotfiles:
        dotfiles_path: /root
    named_run_list: myrun
  - name: path-with-spaces
    attributes:
      chef_dotfiles:
        dotfiles_path: /root/path with spaces
    named_run_list: myrun
