---
driver:
  name: localhost

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: macosx-10
    driver:
      name: localhost

suites:
  - name: default
    attributes:
      chef_dotfiles:
        dotfiles_path: /root
    run_list:
      - test
  - name: path-with-spaces
    attributes:
      chef_dotfiles:
        dotfiles_path: /root/path with spaces
    run_list:
      - test
