---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: windows-2012r2-chef12
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
  - name: default
    attributes:
      chef_dotfiles:
        dotfiles_path: 'C:\Users\vagrant'
    named_run_list: myrun
