---
driver:
  name: dokken
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  sudo: true

platforms:
- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: fedora-22
  driver:
    image: fedora:22
    pid_one_command: /sbin/init
    intermediate_instructions:

suites:
  - name: default
    run_list:
    - recipe[test::default]
