---
driver:
  name: localhost

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: macosx-10
    driver:
      name: localhost
  - name: windows-2012R2

suites:
  - name: default
    verifier:
      inspec_tests:
        - name: test/integration/default/inspec
    run_list:
      - test
