---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: 5985
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero

platforms:
  - name: windows-10
    driver_config:
      box: chef/windows-10-enterprise
  - name: windows-2012R2
  - name: windows-2012r2-chef12
    driver_config:
      box: chef/windows-server-2012r2-standard
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[test::default]
    attributes:
