notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always

language: ruby

sudo: required

matrix:
  include:
  - os: osx
    rvm: 2.3.1
    osx_image: xcode8.3

script:
- KITCHEN_YAML=.kitchen.localhost.yml bundle exec kitchen verify macosx

branches:
  only:
  - macosx
