sudo: required
dist: trusty

language: ruby

group: edge

addons:
  apt:
    sources:
    - chef-current-trusty
    packages:
    - chefdk

matrix:
  include:
  - os: osx
    rvm: 2.3.1
    osx_image: xcode9
  - os: osx
    rvm: 2.3.1
    osx_image: xcode8.3
  - os: osx
    rvm: 2.3.1
    osx_image: xcode8.2
  - os: osx
    rvm: 2.3.1
    osx_image: xcode7.3

services: docker

env:
  matrix:
  - INSTANCE=default-centos-7
  - INSTANCE=default-debian-711
  - INSTANCE=default-opensuse-leap
  - INSTANCE=default-fedora-latest
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-fedora-22
  - INSTANCE=path-with-spaces-ubuntu-1604

before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- /opt/chefdk/embedded/bin/chef --version
- /opt/chefdk/embedded/bin/cookstyle --version
- /opt/chefdk/embedded/bin/foodcritic --version
- /opt/chefdk/embedded/bin/chef gem install kitchen-dokken

script:
- KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
  - script:
    - /opt/chefdk/bin/chef exec delivery local all
    env: UNIT_AND_LINT=1

branches:
  only:
  - master
