language: ruby

sudo: required

install:
  - curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk
  - chef exec bundle install --without=development integration

matrix:
  include:
  - os: osx
    rvm: 2.3.1
    osx_image: xcode8.2

before_script:
  - chef gem install rake
  - export PATH=$PATH:/Users/travis/.chefdk/gem/ruby/2.3.0/bin

script:
- KITCHEN_YAML=.kitchen.localhost.yml bundle exec kitchen verify macosx

branches:
  only:
  - macosx
