language: ruby
cache: bundler

sudo: required
dist: trusty

group: edge

addons:
  apt:
    sources:
    - chef-current-trusty
    packages:
    - chefdk

matrix:
  include:
  - os: osx
    rvm: 2.3.1
    osx_image: xcode9
  - os: osx
    rvm: 2.3.1
    osx_image: xcode8.3
  - os: osx
    rvm: 2.3.1
    osx_image: xcode8.2
  - os: osx
    rvm: 2.3.1
    osx_image: xcode7.3

services: docker

env:
  global:
    - KITCHEN_YAML: .kitchen.dokken.yml
  matrix:
  - INSTANCE=default-centos-7
  - INSTANCE=default-debian-711
  - INSTANCE=default-opensuse-leap
  - INSTANCE=default-fedora-latest
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-fedora-22
  - INSTANCE=path-with-spaces-ubuntu-1604

before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
- eval "$(chef shell-init bash)"
- chef --version
- cookstyle --version
- foodcritic --version
- chef gem install kitchen-dokken

script:
- kitchen verify ${INSTANCE}

matrix:
  include:
  - script:
    - chef exec delivery local all
    env: UNIT_AND_LINT=1

branches:
  only:
  - master
