sudo: required
dist: trusty

group: edge

addons:
  apt:
    sources:
    - chef-current-trusty
    packages:
    - chefdk

matrix:
  include:
  - os: osx
    rvm: 2.3.1
    osx_image: xcode9
  - os: osx
    rvm: 2.3.1
    osx_image: xcode8.3
  - os: osx
    rvm: 2.3.1
    osx_image: xcode8.2
  - os: osx
    rvm: 2.3.1
    osx_image: xcode7.3

services: docker

script:
- KITCHEN_LOCAL_YAML=.kitchen.localhost.yml bundle exec kitchen verify macosx

branches:
  only:
  - macosx
